select*from customer_data limit 20;

-- 1) what is the total revenue generated by male vs female customers??
SELECT 
    "Gender",
    SUM("Purchase Amount (USD)") AS revenue
FROM customer_data
GROUP BY "Gender";

--  2)which customers used a discount but still spent more than the average purchase amount ??
SELECT 
    "Customer ID",
    "Purchase Amount (USD)"
FROM customer_data 
WHERE 
    "Discount Applied" = 'Yes'
    AND "Purchase Amount (USD)" >= (
        SELECT AVG("Purchase Amount (USD)")
        FROM customer_data
    );

--  3)which are the top 5 products with highest average review rating:

select "Item Purchased",Round(avg("Review Rating")) as "Average Product Rating"
from customer_data group by "Item Purchased"
order by avg("Review Rating") desc
limit 5;

-- 4)compare the average purchase amount between standard and express shipping 

select "Shipping Type" , round(avg("Purchase Amount (USD)"))
from customer_data where "Shipping Type" in ('Standard','Express')
group by "Shipping Type"

--  5)do subscribed members spend more ?? compare average spend and total revenue between subscribers and non subcribers

select ("Subscription Status"), count("Customer ID") as total_customers,
round(avg("Purchase Amount (USD)"),2) as avg_spend,
round(sum("Purchase Amount (USD)"),2) as total_revenue
from customer_data
group by "Subscription Status"
order by total_revenue,avg_spend desc;

-- 6) which 5 products have the highest percentage of purchases with discound appiled 

select "Item Purchased",
round(100*Sum(case when "Discount Applied"= 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_data
group by "Item Purchased"
Order by  discount_rate desc
limit 5;

-- 7)segment customers into new, returning,and loyal based on thier total 
--number of previous purchases and show the count of each segment 
with customer_type as (
select "Customer ID","Previous Purchases",
case 
when "Previous Purchases"=1 then 'New'
when "Previous Purchases" between 2 and 10 then 'Returning '
else 'loyal'
end as customer_segment
from customer_data
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- 8)what are the top 3 most purchased products within each category ??

with item_counts 
as (
select "Category","Item Purchased", 
count("Customer ID") as total_orders,
row_number() over(partition by "Category" order by count("Customer ID") desc) as item_rank 
from customer_data
group by "Category","Item Purchased"
)
select item_rank,"Category","Item Purchased", total_orders
from item_counts
where item_rank<=3;

--9) are customers who are repeat buyers (more than 5  previous purchases) also likely to subscribe??
select "Subscription Status",
count("Customer ID") as repeat_buyers from customer_data
where "Previous Purchases">5
group by "Subscription Status"


-- 10)revenue by season 
SELECT
    "Season",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer_data
GROUP BY "Season"
ORDER BY total_revenue DESC;






-- 